# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: tensorplex
networks:
- id: 1
  start_block: 0
  contracts:
  - name: ERC20BurnMint
    address:
    - 0xE4887Cf30fF3EDb843369f2161FCB7e064ff28f0
    handler: src/EventHandlers.ts
    events:
    - event: Approval(address indexed owner, address indexed spender, uint256 value)
    - event: DefaultAdminDelayChangeCanceled()
    - event: DefaultAdminDelayChangeScheduled(uint48 newDelay, uint48 effectSchedule)
    - event: DefaultAdminTransferCanceled()
    - event: DefaultAdminTransferScheduled(address indexed newAdmin, uint48 acceptSchedule)
    - event: RoleAdminChanged(bytes32 indexed role, bytes32 indexed previousAdminRole, bytes32 indexed newAdminRole)
    - event: RoleGranted(bytes32 indexed role, address indexed account, address indexed sender)
    - event: RoleRevoked(bytes32 indexed role, address indexed account, address indexed sender)
    - event: Transfer(address indexed from, address indexed to, uint256 value)
rollback_on_reorg: false
